### ISSUE TITLE
Ascii Encoding error 

### ISSUE THREAD

**Issue by loge1998** [minimaxir/gpt-2-keyword-generation#10]
When I run the same code with the same data. I got this error.

UnicodeEncodeError: 'ascii' codec can't encode characters in position 6639-6640: ordinal not in range(128)

**Comment by IzHoBX** [comment]
This is a bug in the module "ray". I managed to fix it by going to function_manager.py, line 123, and removes the "ascii" parameter. 
As such unicode encoding will be used by default and that works without issues (at least from my runs).

**Comment by sabirdvd** [comment]
As @IzHoBX said 
replace the line 123 with 
return hashlib.sha1(collision_identifier.encode("ascii", errors='ignore')).digest()
